### ISSUE TITLE
chi....Exception (n_discrete_log_bsgs).  discrete log not found

### ISSUE THREAD

**Issue by tomisilander** [fredrik-johansson/arb#108]
A bit dull question, but any good guesses what is wrong here? (after passing nicely all previous tests) 
 
make[1]: Entering directory '/home/tomi/build/arb-master/acb_dirichlet'
    CC   ../build/acb_dirichlet/test/t-euler_product_real_ui
    CC   ../build/acb_dirichlet/test/t-chi
euler_product_real_ui....PASS
chi....Exception (n_discrete_log_bsgs).  discrete log not found.
../Makefile.subdirs:84: recipe for target '../build/acb_dirichlet/test/t-chi_RUN' failed
make[1]: *** [../build/acb_dirichlet/test/t-chi_RUN] Aborted (core dumped)
make[1]: Leaving directory '/home/tomi/build/arb-master/acb_dirichlet'
Makefile:178: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by fredrik-johansson** [comment]
What version of FLINT do you have? Version >= 2.4 is required, and I believe the n_discrete_log_bsgs function should be present since 2.4

**Comment by tomisilander** [comment]
Thanks for a quick reply.
I used the latest libflint in Ubuntu that claims to be 2.4.4.
ts.

On Fri, Mar 4, 2016 at 12:39 PM, Fredrik Johansson <notifications@github.com
> wrote:

> What version of FLINT do you have? Version >= 2.4 is required, and I
> believe the n_discrete_log_bsgs function should be present since 2.4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fredrik-johansson/arb/issues/108#issuecomment-192246728>
> .
>



-- 
ts.

**Comment by fredrik-johansson** [comment]
Strangely, I'm not getting such an error. Are you by any chance on a 32-bit machine?

Could you try with a git checkout of https://github.com/wbhart/flint2?

Some changes were made to n_discrete_log_bsgs just a few days ago. I understood that they were supposed to improve performance, but perhaps there was a bug that needed fixing too.

If the problem persists, it would be great if you could modify the n_discrete_log_bsgs function to print the inputs for which it's failing.

**Comment by tomisilander** [comment]
Hi,
so my initial error was generated during 'make check' of arb-master. I am
in the 64-bit machine. I am running ubuntu on virtualbox but that is hardly
the
cause. The Flint documentation on the website is for the version 2.4.5
while ubuntu has 2.4.4. but the changelog does not mention
n_discrete_log_bgs
being changed there. Anyway, I'll try a newer flint version (if I can get
it compiled) and let you know how it goes.
ts.


On Fri, Mar 4, 2016 at 2:13 PM, Fredrik Johansson <notifications@github.com>
wrote:

> Strangely, I'm not getting such an error. Are you by any chance on a
> 32-bit machine?
>
> Could you try with a git checkout of https://github.com/wbhart/flint2?
>
> Some changes were made to n_discrete_log_bsgs just a few days ago. I
> understood that they were supposed to improve performance, but perhaps
> there was a bug that needed fixing too.
>
> If the problem persists, it would be great if you could modify the
> n_discrete_log_bsgs function to print the inputs for which it's failing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fredrik-johansson/arb/issues/108#issuecomment-192279415>
> .
>



-- 
ts.

**Comment by tomisilander** [comment]
Hello again,
I installed the new flint like you advised, and then recompiled arb and run
make check and .... everything passed just perfectly.
thanks!
ts.

On Fri, Mar 4, 2016 at 2:27 PM, Tomi Silander <tsilande@gmail.com> wrote:

> Hi,
> so my initial error was generated during 'make check' of arb-master. I am
> in the 64-bit machine. I am running ubuntu on virtualbox but that is hardly
> the
> cause. The Flint documentation on the website is for the version 2.4.5
> while ubuntu has 2.4.4. but the changelog does not mention
> n_discrete_log_bgs
> being changed there. Anyway, I'll try a newer flint version (if I can get
> it compiled) and let you know how it goes.
> ts.
>
>
> On Fri, Mar 4, 2016 at 2:13 PM, Fredrik Johansson <
> notifications@github.com> wrote:
>
>> Strangely, I'm not getting such an error. Are you by any chance on a
>> 32-bit machine?
>>
>> Could you try with a git checkout of https://github.com/wbhart/flint2?
>>
>> Some changes were made to n_discrete_log_bsgs just a few days ago. I
>> understood that they were supposed to improve performance, but perhaps
>> there was a bug that needed fixing too.
>>
>> If the problem persists, it would be great if you could modify the
>> n_discrete_log_bsgs function to print the inputs for which it's failing.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fredrik-johansson/arb/issues/108#issuecomment-192279415>
>> .
>>
>
>
>
> --
> ts.
>



-- 
ts.
