### ISSUE TITLE
Configurable number of test iterations

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#111]
It would be nice to have a way to run all tests with 1/10x (or 10x for the paranoid) the default number of iterations.

It would also be nice to be able to list the elapsed time and memory usage for each test.

**Comment by rickyefarr** [comment]
Just curious about the best way of going about this.  It seems like a simple fix, at least for the number of iterations.  The idea is to use the processor to define the number of iterations.  Would this suffice or were you thinking of something different?

**Comment by fredrik-johansson** [comment]
Changing the number of iterations now works by setting ARB_TEST_MULTIPLIER. This just needs to be documented.

**Comment by rickyefarr** [comment]
Ah, I see.  I thought that ARB_TEST_MULTIPLIER was set at compile time, but it's simply set by an environment variable.
