### ISSUE TITLE
arb_intersection

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#114]
I see that there is an `arb_union` but not an `arb_intersection`. FWIW I would use this in my own code for the multivariate interval newton method.

**Comment by fredrik-johansson** [comment]
How would you define the intersection of two disjoint balls?

**Comment by argriffing** [comment]
Maybe use an integer return value?

**Comment by argriffing** [comment]
Oh github is adding likes and votes to comments... not sure how I feel about that.  Maybe &#x1f44e;

**Comment by fredrik-johansson** [comment]
Yes, that sounds like a sensible interface.
