### ISSUE TITLE
exact arb_set_str

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#117]
It doesn't seem to support `ARF_PREC_EXACT`.

```c
#include "arb.h"

void main()
{
    arb_t x;
    arb_init(x);

    arb_set_str(x, "1.5 +/- 0.5", 32);
    arb_print(x); flint_printf("\n");

    arb_set_str(x, "1.5 +/- 0.5", ARF_PREC_EXACT);
    arb_print(x); flint_printf("\n");

    arb_clear(x);
}
```

```
(3 * 2^-1) +/- (536870913 * 2^-30)
Segmentation fault (core dumped)
```

**Comment by rickyefarr** [comment]
Running the code above, I have the same issue.  When I print the value of ARF_PREC_EXACT using 

> printf("ARF_PREC_EXACT = %ld \n", ARF_PREC_EXACT);

I get 9223372036854775807, which is much too large.

Note, this value is defined in arf.h, with:

> /* Allow 'infinite' precision for operations where a result can be computed exactly. */
> #define ARF_PREC_EXACT WORD_MAX

In a similar vein, I'm curious about the following line in arf.h:

> #define ARF_PREC_ADD(prec,extra) ((prec) == ARF_PREC_EXACT ? ARF_PREC_EXACT : (prec) + (extra))

Is this correct?  It appears as though the precision could exceed ARF_PREC_EXACT.

**Comment by fredrik-johansson** [comment]
ARF_PREC_EXACT is not a legal input in general. It's basically only allowed in operations that always can be done without rounding (add, multiply, assign integers), and even then it is unsafe unless you know something about the inputs, because the exponents could be too large. I guess this should be documented more clearly. The largest allowed normal precision is much lower.

**Comment by fredrik-johansson** [comment]
I made a clarification in the documentation.

**Comment by argriffing** [comment]
My reading of this clarification is that the operation of 'conversion from string to arb' doesn't support ARF_PREC_EXACT because this conversion is not an exact operation for all possible inputs (even though it is exact for the specific input "1.5 +/- 0.5").
