### ISSUE TITLE
Suggested route of installation.  With MPIR or without?

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#119]
According to the documentation, the library can be installed using GMP or MPIR, but doesn't discuss the pros or cons of using MPIR verses plain GMP.  The documentation states: 

> If MPIR is used instead of GMP, it must be compiled with the --enable-gmpcompat option.

If MPIR is installed in this way, does it lead to speed gains?  I guess this may depend on the CPU?

**Comment by fredrik-johansson** [comment]
You have to test for yourself whether one is faster on your computer. I don't think it's possible to give any general recommendations.
