### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#122]
If FLINT manages to change the license to LGPL (see https://github.com/wbhart/flint2/issues/244), then Arb could change its license too, assuming that no one who has contributed a substantial amount of code (Alex, Pascal?) objects.

**Comment by certik** [comment]
Thank you for doing that.

**Comment by fredrik-johansson** [comment]
Done. (Still waiting for a LGPL version of FLINT to link against, but that should be in the FLINT git repository in a moment now.)
