### ISSUE TITLE
Make check failure

### ISSUE THREAD

**Issue by isuruf** [fredrik-johansson/arb#124]
```
make[1]: Entering directory `/home/travis/build/isuruf/arb/acb_dirichlet'
    CC   ../build/acb_dirichlet/test/t-chi
    CC   ../build/acb_dirichlet/test/t-euler_product_real_ui
chi....Exception (n_discrete_log_bsgs).  discrete log not found.
```

See entire log here,
https://api.travis-ci.org/jobs/119999378/log.txt?deansi=true

**Comment by fredrik-johansson** [comment]
This is possibly fixed in the git version of flint.

Anyway, Pascal is currently working on new discrete logarithm code for use in the acb_dirichlet module. The failure should go away when merging his branch.

**Comment by isuruf** [comment]
Closing because this is fixed in git version of flint
