### ISSUE TITLE
Add Testing and Benchmark Suite

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#138]
It would be nice to create a benchmark and testing suite.  This would be useful for several purposes and depending on the implementation could fix issue #111 and help with issue #92.  It could also be possible to use the suite for tuning of algorithms.  It would be nice to implement this so that two algorithms can be compared in terms of memory usage and time spent, and plotted using gnuplot. GMPBench could serve as a starting point of implementation.  

Are there any suggestions or ideas?  Is this a worthwhile endeavor for Arb or should this be developed separately from Arb and then perhaps included later?

**Comment by fredrik-johansson** [comment]
I've been doing ad-hoc benchmarking, but a more systematic benchmark suite could be nice to have. GMP and MPFR both have one.

There are a few problems with creating this kind of 

microbenchmarks

Computer

**Comment by rickyefarr** [comment]
Good point.  I'm not sure.

When I wrote this, I imagined a suite that given a function f and it's constant parameters, param, of the form f(input1, input2, input3, ... , inputN, const void * param) would generate input1, input2, ..., inputN randomly and return the average amount of time to evaluate it.

Maybe the suite could accept a function that represents a metric to interpret the results?
