### ISSUE TITLE
Wording of arb_eq and similar function documentation

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#139]
Assuming "normal input" for x and y, i.e. no infinity and NaN cases for midpoint or radius.  Am I correct in saying that arb_eq(x,y) can never be positive if the set x or the set y contain more than one point?

So, in other words arb_eq(x,x) is always zero if the set x contains more than one point?

**Comment by fredrik-johansson** [comment]
Yes, that's correct.

**Comment by rickyefarr** [comment]
I understand the idea behind arb_eq, and similar functions, but it's confusing using eq, gt, lt, in my opinion.

The reason I say this, is because without reading the documentation very carefully, one could be led to believe that one of arb_lt or arb_ge would be true.  I don't think this is the case.

**Comment by rickyefarr** [comment]
I'm not sure of any practical ways of making this more clear.  It seems like this is already the best possible way of doing it, although I still think that this can be confusing since intuition suggests that one of gt or lt would be true.  Then again, it makes sense why it's not the case topologically.

For this reason, I close this issue unless anyone can think of any ideas.
