### ISSUE TITLE
`arb_can_round_arf` is returning false negative?

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#145]
I guess this is documented as "This function may perform a fast, inexact test; that is, it may return zero in some cases even when correct rounding actually is possible." but is there a way I can ask arb to do it more carefully?

Here is the example:

```c
#include "arb.h"

int
main()
{
    arb_t x;
    arb_init(x);

    /* the mid of x is near 0.01 and is exactly representable in double precision */
    arb_set_d(x, 0.01);

    /* add a tiny error radius to x */
    arb_add_error_2exp_si(x, -100000);

    flint_printf("x: "); arb_printd(x, 100); flint_printf("\n");
    flint_printf("x: "); arb_print(x); flint_printf("\n");

    /* x cannot be rounded to the nearest double precision number? */
    flint_printf("can round: %d\n",
            arb_can_round_arf(x, 53, ARF_RND_NEAR));

    arb_clear(x);
    return 0;
}
```

```
x: 0.01000000000000000020816681711721685132943093776702880859375 +/- 1.001e-30103
x: (5764607523034235 * 2^-59) +/- (536870912 * 2^-100029)
can round: 0
```

I understand that if you want to round up or down then it's a problem when `x` is near an exactly representable point, but shouldn't it be OK when rounding to nearest?

**Comment by fredrik-johansson** [comment]
It doesn't just determine whether you can round it correctly; it also determines whether you can determine the correct MPFR ternary value, i.e. whether the result is exact. So you need to know by some other means at which input points the function value is an exact floating-point number.

Note that even if you detect that rounding is possible in this case (without knowing whether the result is exact or inexact), you still face the table-maker's dilemma in other cases (rounding to p nearest bits when the exact value has p+1 bits)

**Comment by argriffing** [comment]
Thanks, I should have paid more attention to `Moreover, arf_get_mpfr() is guaranteed to return the correct ternary value according to MPFR semantics.` in the `arb_can_round_arf()` docs.
