### ISSUE TITLE
complex_plot - file names

### ISSUE THREAD

**Issue by adammaj1** [fredrik-johansson/arb#171]
[complex_plot.txt](https://github.com/fredrik-johansson/arb/files/602126/complex_plot.txt)
Hi,

Now complex plot saves file with the same name.
What about changing it to calling file : 
filename = function+color_mode+".ppm"

like 
``
    char name[30];		
    char cm[10]; // for color_mode
//....
 else if (!strcmp(argv[i], "sin"))
        {
            func = acb_sin;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "gamma"))
        {
            func = acb_gamma;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "digamma"))
        {
            func = acb_digamma;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "lgamma"))
        {
            func = acb_lgamma;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "zeta"))
        {
            func = acb_zeta;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "erf"))
        {
            func = acb_hypgeom_erf;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "ai"))
        {
            func = ai;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "bi"))
        {
            func = bi;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "besselj"))
        {
            func = besselj;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "bessely"))
        {
            func = bessely;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "besseli"))
        {
            func = besseli;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "besselk"))
        {
            func = besselk;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "modj"))
        {
            func = modj;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "modeta"))
        {
            func = acb_modular_eta;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "barnesg"))
        {
            func = acb_barnes_g;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "agm"))
        {
            func = acb_agm1;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "fresnels"))
        {
            func = fresnels;
            strncpy(name, argv[i], sizeof name);
        }
        else if (!strcmp(argv[i], "fresnelc"))
        {
            func = fresnelc;
            strncpy(name, argv[i], sizeof name);
        }
// .....
// filename = function+color_mode+".ppm"
    snprintf(cm, sizeof cm , "%d", color_mode);
    filename = strncat (name, cm, 1);
    filename = strncat (filename, ".ppm", 4);
    fp = fopen(filename, "w");
    fprintf(fp, "P6\n%ld %ld 255\n", xnum, ynum);
```

Then after : 
```./complex_plot  -size 200 200 -color 1 sin```

file will be :  sin1.ppm

Adam

**Comment by fredrik-johansson** [comment]
I think the syntax should just be `-file filename.ppm` (without any string manipulation).

You could also just do `mv arbplot.ppm filename.ppm`.

**Comment by adammaj1** [comment]
OK. Thx
