### ISSUE TITLE
missing Lambert W function

### ISSUE THREAD

**Issue by crowlogic** [fredrik-johansson/arb#173]
with so many transcendental functions implemented in this library it seems like a Lambert W function implementation would fit in well. It can be implemented with Newtons method or Halley's method. https://en.wikipedia.org/wiki/Lambert_W_function

**Comment by crowlogic** [comment]
added a basic implementation based on the Newton iteration with the Java/JNA wrapped version of arblib at

https://github.com/crowlogic/fastmath/blob/9d74c7b889d0a7e8af6d9ed4672a1e269f932c46/src/fastmath/arb/Complex.java#L468

**Comment by fredrik-johansson** [comment]
I have implemented the Lambert W function for real variables in b30933ace9762d1de6ffd56fb579230604267330.

It could be done for complex variables too, but it's a bit more complicated due to the branch cuts (and I would not bother optimizing it as much).

**Comment by fredrik-johansson** [comment]
Done for complex variables in d77b6c5c731a4a3a08fee8a5c0930c7277f98ce4 (although there are some improvements left) and for power series in 9329279e8f69f63b0460be21a60a3e8b76f14bf1.
