### ISSUE TITLE
make examples 

### ISSUE THREAD

**Issue by adammaj1** [fredrik-johansson/arb#177]
Hi,

After 
git pull 

I have : 

a@zelman:~/arb$ make examples
make[1]: Wejście do katalogu '/home/a/arb'
make[1]: Nie ma nic do zrobienia w 'shared'.
make[1]: Opuszczenie katalogu '/home/a/arb'
make[1]: Wejście do katalogu '/home/a/arb'
make[1]: Nie ma nic do zrobienia w 'static'.
make[1]: Opuszczenie katalogu '/home/a/arb'
mkdir -p build/examples
examples/complex_plot_m.c: In function ‘main’:
examples/complex_plot_m.c:226:5: error: C++ style comments are not allowed in ISO C90
     //
     ^
examples/complex_plot_m.c:226:5: error: (this will be reported only once per input file)
examples/complex_plot_m.c:409:5: warning: implicit declaration of function ‘snprintf’ [-Wimplicit-function-declaration]
     snprintf(cm, sizeof cm , "%d", color_mode);
     ^
Makefile:122: polecenia dla obiektu 'examples' nie powiodły się
make: *** [examples] Błąd 1

Adam

**Comment by fredrik-johansson** [comment]
The error message says that you have a C++ style comment (`//`) in your code.

The example programs are compiled in C90 mode, so only C style comments `/* */` are allowed.

**Comment by adammaj1** [comment]
right. thx. I have my old c program in this dir.
