### ISSUE TITLE
arb_set_str interprets decimal input with trailing zeros as exact

### ISSUE THREAD

**Issue by bennybp** [fredrik-johansson/arb#188]
The `arb_set_str` function seems to interpret decimals which end up having trailing zeros as having infinite precision. I am wondering if this is expected behavior, and if so, what the best workaround would be?

Another way of asking the question: How can I tell arb that something like "300" or "300.0" is known only to a given precision? (aside from manually specifying it with +/-)

    arb_t x;
    arb_init(x);

    arb_set_str(x, "1.0", 128);      // x is exact
    arb_set_str(x, "9.2", 128);      // x has 126 bits of precision
    arb_set_str(x, "9.2e3", 128);    // x is exact

    arb_set_round(x, x, 128);        // x still is exact

    arb_clear(x);

**Comment by fredrik-johansson** [comment]
This is the intended behavior, and you do need to specify the error with +/- (alternatively, you could assign the error to a separate variable and then use arb_add_error).

I suppose an alternative function could be added that interprets the last digit as having 1 ulp uncertainty.

**Comment by bennybp** [comment]
Thanks for the quick reply. After thinking about it for a bit, I see where the current behavior make sense. Adding the error to the last place is basically what I was going for, and is something that I can do on my end if you prefer (rather than put it in arb)
