### ISSUE TITLE
Bug in arb_get_abs_lbound_arf ?

### ISSUE THREAD

**Issue by deinst** [fredrik-johansson/arb#199]
It could be that I am misunderstanding the documentation but I'd expect the code

    #include "arb.h"

    int main()
    {
        arb_t oneish;
        arf_t lbound;
        arb_init(oneish);
        arf_init(lbound);
        arb_set_si(oneish, 1);
        arb_add_error_2exp_si(oneish, -100);
        arb_printd(oneish, 20);
        flint_printf("\n");
        arb_get_lbound_arf(lbound, oneish, 32);
        arf_printd(lbound, 20);
        flint_printf("\n");
        arb_get_abs_lbound_arf(lbound, oneish, 32);
        arf_printd(lbound, 20);
        flint_printf("\n");
        if (arf_equal_si(lbound, 1)) {
           flint_printf("It is one!\n");
        }
        arb_clear(oneish);
        arf_clear(lbound);
    }

To result in something like

    1 +/- 7.8886e-31
    0.99999999976716935635
    0.99999999976716935635

Instead I get

    1 +/- 7.8886e-31
    0.99999999976716935635
    1
    It is one!

This is easy for me to work around (just use `arb_get_lbound_arf` and be careful of the sign).

I suspect that the `ARF_RND_UP` on line 300 of `arb.h` should be an `ARF_RND_DOWN` (and a similar error looks like it happens in `arb_get_abs_ubound_arf`, I haven't tested it.

**Comment by fredrik-johansson** [comment]
Yes, that is very much a bug! (arb_get_abs_ubound_arf should be correct, though.) Thanks a lot for reporting it. This is what happens when you skip test code. It's remarkable that it was never caught indirectly by some other tests.

**Comment by deinst** [comment]
Thanks for fixing it so quickly.
