### ISSUE TITLE
free() call crashes inside  arb_calc_newton_conv_factor  

### ISSUE THREAD

**Issue by crowlogic** [fredrik-johansson/arb#200]
```Core was generated by `/usr/lib/jvm/oracle-java8-jdk-amd64/bin/java -ea -ea -Dfile.encoding=UTF-8 -cla'.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x7fe54260a700 (LWP 22892))]
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fe541a47f5d in __GI_abort () at abort.c:90
#2  0x00007fe5413423b5 in ?? () from /usr/lib/jvm/oracle-java8-jdk-amd64/jre/lib/amd64/server/libjvm.so
#3  0x00007fe5414e4673 in ?? () from /usr/lib/jvm/oracle-java8-jdk-amd64/jre/lib/amd64/server/libjvm.so
#4  0x00007fe5413478bf in JVM_handle_linux_signal () from /usr/lib/jvm/oracle-java8-jdk-amd64/jre/lib/amd64/server/libjvm.so
#5  0x00007fe54133de13 in ?? () from /usr/lib/jvm/oracle-java8-jdk-amd64/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  0x00007fe541a9e3f4 in __GI___libc_free (mem=<optimized out>) at malloc.c:3143
#8  0x00007fe510503855 in flint_free (ptr=<optimized out>) at memory_manager.c:98
#9  0x00007fe510a7e209 in _arf_demote (x=<optimized out>) at memory_manager.c:95
#10 0x00007fe510abd9e5 in arb_clear (x=x@entry=0x7fe542607a80) at clear.c:20
#11 0x00007fe510af429a in arb_calc_newton_conv_factor (conv_factor=0x7fe53c277300, func=<optimized out>, param=<optimized out>, conv_region=<optimized out>, prec=128) at newton_conv_factor.c:32
#12 0x00007fe510ec6564 in ?? ()
#13 0x0000000000000000 in ?? ()
```

**Comment by crowlogic** [comment]
[crash.txt](https://github.com/fredrik-johansson/arb/files/1561434/crash.txt)

**Comment by fredrik-johansson** [comment]
I don't see anything problematic with this function. You are probably missing an initialization somewhere else.

**Comment by crowlogic** [comment]
Ahh, it has something to do with the way structures are mapped by value or pointer with JNA. Thank you
