### ISSUE TITLE
expm1 interval is kind of wide for some inputs

### ISSUE THREAD

**Issue by arbguest** [fredrik-johansson/arb#214]
```
x : -1e+06 +/- 2
expm1(x) : -1 +/- 12.778
exp(x) - 1 : -1 +/- 5.421e-20
```

**Comment by fredrik-johansson** [comment]
Indeed. Note that I optimized the intervals for arb_exp recently. Both arb_expm1 and arb_exp_expinv should get a similar treatment, but I didn't have time.

**Comment by arbguest** [comment]
After looking at this again I almost feel like there is a bug in the expm1 implementation that gives large radii for negative non-tiny x. I tried making a change to the function (https://github.com/arbguest/arb/commit/bebac3c79ec824f6f5240cc2d6d2b58f80bbb3f6) and got the following results:

```
x : 1e-10 +/- 6.3109e-30
old expm1(x): 1e-10 +/- 1.2646e-29
new expm1(x): 1e-10 +/- 1.2646e-29
exp(x) - 1  : 9.999999993e-11 +/- 1.0863e-19

x : -1e-10 +/- 6.3109e-30
old expm1(x): -1e-10 +/- 1.2646e-29
new expm1(x): -1e-10 +/- 1.2646e-29
exp(x) - 1  : -1e-10 +/- 5.4422e-20

x : 10.4 +/- 8.6736e-19
old expm1(x): 32858.62567 +/- 3.2061e-14
new expm1(x): 32858.62567 +/- 3.2061e-14
exp(x) - 1  : 32858.62567 +/- 3.2061e-14

x : -10.4 +/- 8.6736e-19
old expm1(x): -0.9999695675 +/- 1.7889e-18
new expm1(x): -0.9999695675 +/- 5.4237e-20
exp(x) - 1  : -0.9999695675 +/- 5.4238e-20

x : -1000.4 +/- 5.5511e-17
old expm1(x): -1 +/- 1.1108e-16
new expm1(x): -1 +/- 5.421e-20
exp(x) - 1  : -1 +/- 5.421e-20

x : -100000.4 +/- 7.1054e-15
old expm1(x): -1 +/- 1.4211e-14
new expm1(x): -1 +/- 5.421e-20
exp(x) - 1  : -1 +/- 5.421e-20

x : 1000000 +/- 2
old expm1(x): 3.033215397e+434294 +/- 1.9379e+434295
new expm1(x): 3.033215397e+434294 +/- 1.9379e+434295
exp(x) - 1  : 1.143325935e+434295 +/- 1.1023e+434295

x : -1000000 +/- 2
old expm1(x): -1 +/- 12.778
new expm1(x): -1 +/- 7.4691e-19
exp(x) - 1  : -1 +/- 5.421e-20
```

The old and new expm1 are similar to each other for large positive x and for very small absolute value x, but the new one is much better for non-tiny negative x. All MOD=arb tests still pass. This issue doesn't only affect inputs that have wide intervals, it also affects inputs with small intervals. To me it looks like part of the code was intended to have been like abs((exp(x) - 1) + 1) but it was written instead as abs(exp(x) - 1) + 1 which gives valid but unnecessarily loose bounds.

**Comment by fredrik-johansson** [comment]
That seems right. It might be possible to implement this without the arb_add_ui operation, though. If not fixed sooner, I will fix this when I optimize arb_expm1 like arb_exp.

**Comment by fredrik-johansson** [comment]
Should be done in commit f00f00c.
