### ISSUE TITLE
Xi(z) = xi(1/2 + z*i)

### ISSUE THREAD

**Issue by p15-git-acc** [fredrik-johansson/arb#221]
Would you be interested in having the capital Riemann Xi function alongside the lowercase one?
https://en.wikipedia.org/wiki/Riemann_Xi_function
The reasons not to, would be if it pollutes the namespace too much or increases the build and test time and docs length for such a trivial wrapper function, and I don't know if you even allow capital letters in your c file names.

**Comment by fredrik-johansson** [comment]
I think it's a too trivial variation of the lowercase function to be worth it.
