### ISSUE TITLE
What is the best way to hardcode in C an array of arb_t numbers ?

### ISSUE THREAD

**Issue by jgmbenoit** [fredrik-johansson/arb#225]
I am looking for hardcoding an array of arb_t numbers in C.

**Comment by fredrik-johansson** [comment]
What do you mean by hardcoding? It's possible to do this:

    arb_ptr vec;
    vec = _arb_vec_init(10);
    _arb_vec_clear(vec, 10);

Or this:

    arb_struct vec[10];
    for (i = 0; i < 10; i++)
        arb_init(vec + i);

    for (i = 0; i < 10; i++)
        arb_clear(vec + i);

**Comment by jgmbenoit** [comment]
Let be precise. With double, I will do:

const double tableof_precious_number[]={
3., 3.1, 3.14, [..] };
Can we do something similar wit arb_t numbers ?
It takes some times to compute the table, so I want to encode it for once.

**Comment by fredrik-johansson** [comment]
In what form are the numbers given, precisely? Many times, the most convenient way to do this would be to encode the data as a table of double constants, or strings if you need higher precision. Then write a function that sets the entries of your arb vector with arb_set_d or arb_set_str, and call it just once in your program before you need to use the vector the first time.

**Comment by jgmbenoit** [comment]
I came to this solution too. So I will hard code my table in string.
