### ISSUE TITLE
Implementation of elliptic functions/integrals

### ISSUE THREAD

**Issue by bluescarni** [fredrik-johansson/arb#23]
Not really an issue, more like a hopefully polite request :)

I am an enthusiastic user of the elliptic functions/integrals module in mpmath. Any plans for implementing them in arb as well?

**Comment by fredrik-johansson** [comment]
I've implemented incomplete elliptic integrals. Also, the various elliptic integrals and functions are now in their own module: http://arblib.org/acb_elliptic.html

**Comment by fredrik-johansson** [comment]
Added the Weierstrass zeta and sigma functions for good measure.

**Comment by fredrik-johansson** [comment]
And finally, I implemented the inverse Weierstrass function. This issue seems safe to close now (though we could still add more notational versions, e.g. the various Jacobi elliptic functions).
