### ISSUE TITLE
coulomb function

### ISSUE THREAD

**Issue by MacroUniverse** [fredrik-johansson/arb#252]
Hi,
Could you implement the [coulomb radial functions (F, G, H+,H-)](https://www.sciencedirect.com/science/article/pii/S0010465506003717) and the [coulomb function (asymptotic plane wave)](
https://en.m.wikipedia.org/wiki/Coulomb_wave_function)? I understand both can be represented using hypergeometric functions (whittakerM/U, 1F1, gamma, etc.), but directly implementing it might result in a better performance.

**Comment by fredrik-johansson** [comment]
To clarify, all the functions can be computed via the 1F1 and U hypergeometric functions and log-gamma functions, and I don't think it should be done in any other way. It's just a question of working out which combinations of formulas to use.

**Comment by fredrik-johansson** [comment]
Implemented in 8223465324a578692addbd4ab4489d6398392009 but still needs a bit of work.

**Comment by MacroUniverse** [comment]
Thank you, this is great! I'll test it soon.

**Comment by jagot** [comment]
I am also interested in these functions! In particular, I'm interested the function value and its first derivative at a specific coordinate. Is it possible to calculate the latter using [`acb_hypgeom_coulomb_series`](https://github.com/fredrik-johansson/arb/blob/master/acb_hypgeom/coulomb_series.c#L74) (I'm still new to Arb, so I don't know my way around yet)?

There are a few different possible normalizations as well, which one is it that's implemented in Arb?

**Comment by fredrik-johansson** [comment]
Correct. You can also use acb_hypgeom_coulomb_jet if you just need the direct derivatives a specific coordinate. Like this:

len = 2; // F and F'
acb_ptr F = _acb_vec_init(len);
acb_ptr G = _acb_vec_init(len);   // or G = NULL if you just want F
acb_coulomb_jet(F, G, NULL, NULL, l, eta, z, len, prec);
acb_printn(F + 0, 20, 0); // F
acb_printn(F + 1, 20, 0); // F'
acb_printn(G + 0, 20, 0); // G
acb_printn(G + 1, 20, 0); // G'
...

You should be able to do this with ccall code in Nemo without too much trouble; look at the existing wrappers in acb.jl.

The normalization is the usual one for F and G described in https://dlmf.nist.gov/33.2

I just rebuilt the web docs so the functions are now documented at http://arblib.org/acb_hypgeom.html#coulomb-wave-functions and http://arblib.org/arb_hypgeom.html#coulomb-wave-functions .
