### ISSUE TITLE
whittaker shannon interpolation for platt zeta zeros can be sped up

### ISSUE THREAD

**Issue by p15-git-acc** [fredrik-johansson/arb#284]
Whittaker-Shannon interpolation makes repeated calls to sinc(x)=sin(x)/x, where the argument of each call is offset by an integer multiple of pi. This means that the sine factor of sinc should be reusable, which should speed up the interpolation by about 20%-25% according to the proportion of time spent by arb_sin_pi as recorded by callgrind in an example.

**Comment by simonpuchert** [comment]
This can be done by handling the term `c(t + n) * sin(pi * (t+n)) / (pi * (t+n))` with `|t+n| < 1/2` separately (so you don't divide by zero) and then factoring out `sin(pi * t) / pi`, so for the other terms you would just sum up `(-1)^n * c(t+n) / (t+n)`.
