### ISSUE TITLE
acb_calc_integrate gives wrong results when integrating over a line with complex endpoints

### ISSUE THREAD

**Issue by SerendipityAbound** [fredrik-johansson/arb#293]
I'm using SageMath 8.8 via its Jupyter notebook and when I used its interface to Arb and tried the following integral:
```
print CBF.integral(lambda x, _: x.gamma(), 1 - CBF(i), 1 + CBF(i))
```
it gives `[+/- 4.33e-15] + [1.5723926694981 +/- 4.57e-14]*I` which is incorrect. Writing the following code instead returns the correct result:

```
print CBF.integral(lambda x, _: (1+x*im).gamma(), -1, 1)
```
outputs `[1.5723926694981 +/- 4.57e-14] + [+/- 4.33e-15]*I`.
The bug persists when using Arb that I built from the latest commit so the bug isn't in SageMath interface to Arb.

**Comment by fredrik-johansson** [comment]
Both results are correct. Integrals are oriented; if you rotate the path of integration by i, you also pick up a factor i in the value of the integral.

**Comment by SerendipityAbound** [comment]
Right, that's what I get for self-studying things and skipping from topic to topic - forgetting that parametrization matters. Nonetheless, thanks.
