### ISSUE TITLE
CMakeLists.txt wants mpir, gmp not enough

### ISSUE THREAD

**Issue by texnokrates** [fredrik-johansson/arb#296]
README.md says:

> Arb depends on FLINT, either GMP or MPIR, and MPFR

I have gmp (not mpir) installed, however the CMake script wants specifically mpir:
```
CMake Error at CMakeLists.txt:74 (message):
  mpir library not found.
```

**Comment by isuruf** [comment]
CMake script looks for both and that message is given if neither is found. (Error message can be made better)

**Comment by texnokrates** [comment]
Well, then it does a bad job in doing so. Apparently, the problem is the option `NO_DEFAULT_PATH` option in the `find_library` command (combined with wrong `HINTS`; the way the `PLATFORM` variable is set seems weird to me).

Removing the `NO_DEFAULT_PATH` options fixes the problem. I don't know whether there is any good reason to have the option there, but I doubt so.
