### ISSUE TITLE
build issue with flint 2.6.0

### ISSUE THREAD

**Issue by chacha21** [fredrik-johansson/arb#310]
When trying to build arb 2.17.0 with flint 2.6.0, there is a conflict in fmpz_extras.h :
redefinition of 'fmpz_add_si'
and
redefinition of 'fmpz_sub_si'

Those functions are part of flint-2.6.0/fmpz.h, and were not present in previous flint versions.

Deleting those functions in fmpz_extras.h seems to work, but adding a special case for __FLINT_RELEASE >= 20600 will certainly be the good fix

**Comment by fredrik-johansson** [comment]
Thanks for reporting. This is already fixed in the git master, and there will be a new release shortly.
