### ISSUE TITLE
Determining Arb version at compilation time

### ISSUE THREAD

**Issue by bluescarni** [fredrik-johansson/arb#311]
Is it possible to determine the Arb version in use at compile time? E.g., as a preprocessor definition? 

This would be useful to selectively enable/disable code in a library which depends on Arb. For instance, I noticed that the ``acb_agm()`` function was added in 2.18 (if I am not mistaken), but at the moment I don't see any way of knowing if I can refer to/invoke this function purely from within the source code of a library which depends on Arb.

(Such a check can be done at the level of the build system, but it would be useful to have the version information also as preprocessor definitions in the headers)

**Comment by fredrik-johansson** [comment]
I added such version numbers in c72a7ec1e190c9721162e3419bf029625df42167 (copying the format from flint), though they erroneously give the number as 2.18.0 right now. I will try to remember to set them to the right values for the 2.18.1 patch release :-)

**Comment by bluescarni** [comment]
Cheers! Any chance that identifiers starting with double underscore ``__`` could be avoided? Names with leading double underscores are supposed to be reserved for the C/C++ library implementation:

https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier

**Comment by fredrik-johansson** [comment]
I used the same naming convention as Flint (as well as GMP) to keep surprises to a minimum. It's unlikely that it's going to clash with anything else.

**Comment by bluescarni** [comment]
Ok sounds good. Thanks, closing.
