### ISSUE TITLE
arf_get_fmpq is missing from documentation

### ISSUE THREAD

**Issue by saraedum** [fredrik-johansson/arb#318]
`arf_get_fmpq` is in `arf.h` but it's not in `arf.rst`. Is that intentional?

**Comment by p15-git-acc** [comment]
I checked if it's easy to add this documentation, but I'm confused about how to document this part:

```c
    else if (arf_is_special(x) || !ARF_IS_LAGOM(x))
    {
        flint_printf("exception: arf_get_fmpq: cannot convert to rational\n");
        flint_abort();
    }
```

Apparently it aborts the execution if the exponent of the `arf_t` input is too big.
