### ISSUE TITLE
Gauss-Legendre Integration

### ISSUE THREAD

**Issue by rickyefarr** [fredrik-johansson/arb#34]
I have some code that generates Gauss-Legendre quadrature rules.  As of right now, the code returns a struct that contains the length, a node vector, and a weight vector.  Is this something that would be useful to be added into the library?  If so, any suggestions for changes would be appreciated.

The file is located at the following link:

https://github.com/Therickaman/arb/blob/77bacde5db14d2e9d97c77658b32a480415f071b/gaussLegendre.c

The code is pretty rough, but needs discussion.  

Should the radius be set to zero for the weights and nodes, so that they are pretty much treated as exact?  Should the return structure be changed?  To integrate a user defined function f using arb what should the format be when passed to functions that integrate?

**Comment by fredrik-johansson** [comment]
Sorry for the late reply -- just got back from vacation.

Looking at the correction in a step with Newton's method isn't a rigorous way to bound the error. You can have a small correction and still be far away from the root.

It's fine to use heuristics if you validate the result afterwards. In this case, you could verify that there's a sign change on each root's isolating interval and that all intervals are disjoint.

After finding good isolating intervals, arb_calc_refine_root_newton could be used to polish the roots to high precision.
