### ISSUE TITLE
size specifier for integers in unit test format strings

### ISSUE THREAD

**Issue by p15-git-acc** [fredrik-johansson/arb#345]
I see that "%wd" is often used, but I don't think that's a real thing even though it seems to work for me. I guess the idea is that it's a 'wide decimal' but I think it should be changed to "%ld". According to [Microsoft docs](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions) w can be used as a size modifier for characters and strings but it doesn't show it being used for integers. According to [cplusplus.com docs](http://www.cplusplus.com/reference/cstdio/printf/) w is not a valid length sub-specifier for any specifier character.

**Comment by fredrik-johansson** [comment]
This a custom format code used by flint_printf.

**Comment by p15-git-acc** [comment]
Thanks!
