### ISSUE TITLE
windowed zeta zeros function could use better parameter heuristics

### ISSUE THREAD

**Issue by p15-git-acc** [fredrik-johansson/arb#348]
see for example https://github.com/fredrik-johansson/arb/issues/335#issuecomment-701663788

**Comment by rudolph-git-acc** [comment]
With the improved `K=K/2` timings, `n=1e24` was successfully completed in only 14 hours (`prec=256, 64 threads/32 cores`).

![kdiv21e24](https://user-images.githubusercontent.com/36714969/94813906-e5f8e980-03f8-11eb-9436-e1bf64a8d0b2.jpeg)

At `1e24` the number of zeros found starts to slightly decline, so `K/2` could run out of steam here (or it is the `prec`-setting).

[zeros10e24.txt](https://github.com/fredrik-johansson/arb/files/5312231/zeros10e24.txt)

Note that just doubling `B` only had adverse effects, so additional tuning of the other parameters seems required for this case.
