### ISSUE TITLE
Add incomplete gamma functions

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#36]
Gamma(s,z)
gamma(s,z)
gamma*(s,z) (without the z^s factor)

Series expansions with respect to z.

Maybe also regularized incomplete gamma functions.

**Comment by argriffing** [comment]
At least some of these have been added, right?

**Comment by fredrik-johansson** [comment]
Yes, the upper gamma function (Gamma(s,z)) has been added, including regularization. It's missing series expansion (there is a function in acb_poly, but it should be moved to acb_hypgeom and a regularized flag should be added).

The lower gamma function is missing. It's a trivial special case of 1F1, just not with code yet. To keep the number of functions down, I think I would make gamma*(s,z) the result of gamma(s,z,regularized) with regularized=2.
