### ISSUE TITLE
gamma_fmpq test fails on 32-bits with arb 2.21.0

### ISSUE THREAD

**Issue by SnarkBoojum** [fredrik-johansson/arb#379]
It has been reported [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995185) that there's a problem on 32-bits architectures ; indeed [the build logs](https://buildd.debian.org/status/package.php?p=flint-arb) show quite a few problems.

**Comment by fredrik-johansson** [comment]
I didn't catch this because the 32-bit tests on appveyor all passed.

Is there some way to get access to a failing machine?

**Comment by fredrik-johansson** [comment]
I can force a harmless test failure out of t-gamma_fmpq by setting ARB_TEST_MULTIPLIER=100, but this does not seem to be the problem because the build logs above show an abort() without a test failure message.

**Comment by fredrik-johansson** [comment]
I have fixed the harmless bug; can you check if this makes tests pass on some of the machines?

**Comment by tornaria** [comment]
```
$ make BUILD_DIRS=arb TESTS=build/arb/test/t-gamma_fmpq check
[...]
gamma_fmpq....FAIL: poor accuracy

prec = 49
q = -77/19

r = -0.7344533477145 +/- 5.8402e-14

make: *** [Makefile:166: check] Error 134
```

**Comment by SnarkBoojum** [comment]
It's possible to get access to Debian's machines for such work (see [here](https://dsa.debian.org/doc/guest-account/), but it's only temporary and takes some time to get.

I'm compiling 450435a on an armhf box ([abel.debian.org](https://db.debian.org/machines.cgi?host=abel)), so I should hopefully confirm it helps.

@tornaria on which type of box did you give it a try?

**Comment by tornaria** [comment]
> @tornaria on which type of box did you give it a try?

Void linux, i686-glibc. I also tested x86_64-glibc and x86_64-musl (see https://github.com/void-linux/void-packages/pull/33170).

**Comment by SnarkBoojum** [comment]
Everything passed on the armhf box!

**Comment by fredrik-johansson** [comment]
Great. I will wait another day or two just in case any other bug reports come in and then I'll issue 2.21.1.
