### ISSUE TITLE
cl, ARCH=32 failing on Appveyor

### ISSUE THREAD

**Issue by fredrik-johansson** [fredrik-johansson/arb#386]
@isuruf 

ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::chardet-3.0.4-py_1'.

**Comment by albinahlback** [comment]
Did you "solve" this by removing the testing of it?

**Comment by fredrik-johansson** [comment]
No, I removed testing to solve the problem that it doesn't find GMP.
