### ISSUE TITLE
Add `_acb_vec_exp` in order to speed up computations of Fourier series

### ISSUE THREAD

**Issue by albinahlback** [fredrik-johansson/arb#388]
It would be nice to have a function like `_acb_vec_exp(acb_struct * res, acb_t x, slong n)` that evaluates `exp(x), exp(2 x), ..., exp(n x)`. There is some work that has to be made in order to vectorize `a[r/c]b_exp`, but it could shave of some time when computing Fourier series.

**Comment by fredrik-johansson** [comment]
You can use _acb_vec_set_powers for this.

**Comment by albinahlback** [comment]
Yeah, that's true. I was thinking about the precision, but in that case I could just increase the precision. Thanks.
