### ISSUE TITLE
Some tests get stuck on some architectures 

### ISSUE THREAD

**Issue by SnarkBoojum** [fredrik-johansson/arb#402]
Build gets stuck on a few architectures because some tests seem to take ages ; see [logs here](https://buildd.debian.org/status/package.php?p=flint-arb).

**Comment by fredrik-johansson** [comment]
Thanks for reporting. I would need access to a failing machine somehow to debug this.

**Comment by SnarkBoojum** [comment]
That can be arranged: https://dsa.debian.org/doc/guest-account/

**Comment by math-gout** [comment]
Can confirm that ```make test``` gets stuck on arm64. I tried on a Raspberry Pi 4 and a MacBook Air M1.
I don't have logs, but it got stuck when testing ```erf``` in both cases.

**Comment by fredrik-johansson** [comment]
I have fixed a couple of candidate bugs.

**Comment by SnarkBoojum** [comment]
I took your two last commits, made a patch and the package built on arm64 ; I uploaded 2.22.0-2 so we will see if other architectures get likewise fixed [here](https://buildd.debian.org/status/package.php?p=flint-arb).

**Comment by SnarkBoojum** [comment]
As you can see, not perfect, but much better!

**Comment by SnarkBoojum** [comment]
The problem in this report is fixed, I'll open a new one for what remains.
