### ISSUE TITLE
Would you want to have an arb_abs_slow() function?

### ISSUE THREAD

**Issue by postmath** [fredrik-johansson/arb#441]
The documentation for `arb_abs` states that "[n]o attempt is made to improve the interval represented by x if it contains zero". That is of course the right design for the "default" implementation of the abs function. But would it make sense to have an alternative that *does* do this? Something like this:

```
arb_abs_slow(arb_t y, const arb_t x, slong prec) {
  if(arb_is_finite(x) && arb_contains_zero(x)) {
    arb_get_abs_ubound_arf(arb_midref(y), x, prec);
    /* Now t :=arb_midref(y) is the upper bound of the interval x; we need to set arb_midref(y) and arb_radref(y) to (approximations of) t/2.  */
    arf_mul_2exp_si(arb_midref(y), arb_midref(y), -1);
    arf_get_mag(arb_radref(y), arb_midref(y));
    /* Note the above is inexact (rounding up), so need to update arb_midref(y) to match again */
    arf_set_mag(arb_midref(y), arb_radref(y));
  }
  else {
    arf_abs(arb_midref(y), arb_midref(x));
    mag_set(arb_radref(y), arb_radref(x));
  }
}
```
If you like this idea, I'll write it up a bit more nicely, test & document it, and create a pull request. Otherwise we'll implement it in our wrapper library.

**Comment by postmath** [comment]
Maybe we should use `MAG_BITS` instead of `prec` for this, since the second half uses `MAG_BITS` anyway.

**Comment by fredrik-johansson** [comment]
Yes, that would be useful to have. I think there are a few places in the library where this ought to replace ``arb_abs``, too.

**Comment by postmath** [comment]
On it. Would you like to suggest a better name than `arb_abs_slow`, or shall I use that?

**Comment by fredrik-johansson** [comment]
Maybe ``arb_nonnegative_abs`` to match ``arb_nonnegative_part``?

The ``prec`` argument looks redundant.

**Comment by postmath** [comment]
Okay, I'll use that. Yes, I only used `prec` before I realized the
precision would be dropped to `MAG_BITS` anyway.

Erik
