### ISSUE TITLE
reference for elementwise error bounds of matrix exponential?

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#54]
Is it like http://arxiv.org/abs/0908.3954? There's an explanation at http://fredrikj.net/arb/arb_mat.html#c.arb_mat_exp but I don't understand how or why it works.

**Comment by fredrik-johansson** [comment]
It's trivial. We truncate the Taylor series before the term of index N. The infinity norm of the error, $\| \sum_{k=N}^{\infty} A^k / k! \|$, is bounded by $\sum_{k=N}^{\infty} \|A\|^k / k!$. A bound for the infinity norm in turn gives an entrywise bound.

The documentation is actually a bit outdated -- the last sum is now bounded using the function mag_exp_tail, which gives a finite bound even for small values of N.

**Comment by argriffing** [comment]
I think I see the idea. That may be the same method used in that paper? Except (16) in that paper (from (33) in their reference http://www-sbras.nsc.ru/interval/Library/Thematic/Circuits/OppenhMichel-2.pdf) uses a different `mag_exp_tail` bound than in arb:
`(x^N / N!) / (1 - x/(N+1)) when x < N+1`
instead of
`2*x^N / N! when x < N/2`.
Where these domains overlap, the more complicated bound is slightly tighter, up to about a factor of 2. But their tail bound does not always beat exp(x) in their domain. I'm not sure if this bound would be worth adding to arb? Maybe not..

**Comment by fredrik-johansson** [comment]
I didn't implement the more accurate bound in mag_exp_tail yet, but I guess I could do so. I use that version in other places (hypergeometric series). One bit is usually not a big deal.

**Comment by fredrik-johansson** [comment]
I updated the documentation in 682369220962227332b40f30bb2289451aa325ab

Is there anything else that need clarifying, or can I close the issue?

**Comment by argriffing** [comment]
The doc change looks great although I'm not sure how to preview the rendered tex. I assume there is not a rendering problem. I noticed the commit removes `of the Taylor series` from `rapid convergence of the Taylor series` in arb_mat but not in acb_mat. There is also the difference between the old `truncating the Taylor series before term N` vs. the new `truncating the Taylor series after N terms` but I guess these mean the same thing if the first term is term zero.
