### ISSUE TITLE
hilbert_class_poly spam in tests

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#59]
Running `make check` gives many lines that look like test failures, but which I think are more like debugging printfs in non-test code.

`hilbert_class_poly failed at 8837953 bits of precision`

These `hilbert_class_poly` tests are taking a while, but I haven't tried to time them. I'm running the development branch of arb with the lib{flint, gmp, mpfr}-dev that are packaged for Ubuntu 15.04.

**Comment by fredrik-johansson** [comment]
There's a bug somewhere. The hilbert_class_poly test takes 1 second for me. These printouts shouldn't be occurring; the outrageous precision is a hint that something is wrong.

**Comment by argriffing** [comment]
It passes after having built my own FLINT. Maybe the arb tests require a FLINT version newer than the 2.4 suggested in http://fredrikj.net/arb/setup.html?

**Comment by fredrik-johansson** [comment]
This might be the problem: n_gcd takes the operands in any order in flint 2.5, but the version in 2.4 still requires the larger operand to come first.

Could you check if using n_gcd_full instead of n_gcd in hilbert_class_poly.c makes it work with 2.4?
