### ISSUE TITLE
[doc] What is the precision of the midpoint after arb_t operations?

### ISSUE THREAD

**Issue by jdemeyer** [fredrik-johansson/arb#65]
The documentation of `arb_t` doesn't mention what the precision (number of bits) of the midpoint of a ball is after an operation. It says that the internal working precision is not well-defined, but I think at least the output precision should be well-defined.

I guess that after calling some function `arb_foo(arb_t x, ..., long prec)`, the midpoint of `x` will be represented as `prec` bits. Is this guess right? If so, it should be documented.

**Comment by fredrik-johansson** [comment]
That's right almost everywhere. There are some operations where prec is used to specify the accuracy of the output, and the precision can thus be slightly higher.

**Comment by fredrik-johansson** [comment]
This is now explained on http://fredrikj.net/arb/using.html

If any function currently takes a prec parameter and doesn't round the output to prec bits, that should be considered a (minor) bug in need of fixing.
