### ISSUE TITLE
_arb_vec_norm seems to compute the squared norm

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#71]
This can't be right can it? It's like this in the implementation and in the docs. Should the function name be changed to `_arb_vec_squared_norm` or maybe a square root should be taken? I couldn't find where this function is actually called.

**Comment by fredrik-johansson** [comment]
It's not used anywhere. I don't know if anyone uses it externally. I suppose it could be renamed.

**Comment by argriffing** [comment]
According to the original PR https://github.com/fredrik-johansson/arb/pull/6 it's used externally in an LLL implementation somewhere.

**Comment by fredrik-johansson** [comment]
That was a comment about the mathematical operation. The function is not actually used in any implementation as far as I'm aware.
