### ISSUE TITLE
fprint

### ISSUE THREAD

**Issue by argriffing** [fredrik-johansson/arb#80]
Arb can print but not fprint its objects. If this is added, should foo_print_bar(...) call foo_fprint_bar(stdout, ...) or should the print/fprint functions be implemented separately with code duplication?

**Comment by fredrik-johansson** [comment]
> should foo_print_bar(...) call foo_fprint_bar(stdout, ...)

Yes.

You may remove the fmpr and fmprb methods since the types are deprecated,

**Comment by argriffing** [comment]
Thanks, I've made those changes in the PR.
