### ISSUE TITLE
/usr/local/include/nmod_vec.h:37:26: fatal error: ulong_extras.h

### ISSUE THREAD

**Issue by adammaj1** [fredrik-johansson/arb#82]
Hi, I have Ubuntu 14.04 LTS. After installation : https://pl.wikibooks.org/wiki/Programowanie_w_systemie_UNIX/ARB#Instalacja
 I have tried to compile a program from  http://fredrikj.net/arb/setup.html

/*
gcc -I/usr/local/include/flint/  -L/usr/local/include/flint/ -larb c.c
gcc -larb c.c
 gcc -lflint -lgmp -lmpfr -larb -I/usr/include/flint c.c
gcc -I/usr/local/include -I/usr/local/include/flint/ -L/usr/local/lib -larb c.c
gcc -lflint -lgmp -lmpfr -larb -I/usr/local/include -I/usr/local/include/flint/ -L/usr/local/lib  c.c
*/
# include <arb.h>

int main()
{
    arb_t x;
    arb_init(x);
    arb_const_pi(x, 50 \* 3.33);
    arb_printn(x, 50, 0); flint_printf("\n");
    flint_printf("Computed with arb-%s\n", arb_version);
    arb_clear(x);
}

Nothing works : 

 gcc -larb c.c
In file included from /usr/local/include/fmpz.h:45:0,
                 from /usr/local/include/fmpr.h:37,
                 from /usr/local/include/fmprb.h:29,
                 from /usr/local/include/arb.h:36,
                 from c.c:16:
/usr/local/include/nmod_vec.h:37:26: fatal error: ulong_extras.h: Nie ma takiego pliku ani katalogu
 #include "ulong_extras.h"
                          ^
compilation terminated.
a@zalman:~/c/varia/arb/1$ gcc -I/usr/local/include -L/usr/local/lib -larb c.c
In file included from /usr/local/include/fmpz.h:45:0,
                 from /usr/local/include/fmpr.h:37,
                 from /usr/local/include/fmprb.h:29,
                 from /usr/local/include/arb.h:36,
                 from c.c:16:
/usr/local/include/nmod_vec.h:37:26: fatal error: ulong_extras.h: Nie ma takiego pliku ani katalogu
 #include "ulong_extras.h"
                          ^
compilation terminated.
a@zalman:~/c/varia/arb/1$ locate ulong_extras.h
/home/a/flint2/ulong_extras.h
/usr/local/include/flint/ulong_extras.h
a@zalman:~/c/varia/arb/1$ gcc -I/usr/local/include -I/usr/local/include/flint/ -L/usr/local/lib -larb c.c
/tmp/cc9MgIvo.o: In function `_fmpz_demote':
c.c:(.text+0x28): undefined reference to`_fmpz_clear_mpz'
/tmp/cc9MgIvo.o: In function `arf_clear':
c.c:(.text+0xfc): undefined reference to`_arf_demote'
/tmp/cc9MgIvo.o: In function `arb_printn':
c.c:(.text+0x181): undefined reference to`arb_fprintn'
/tmp/cc9MgIvo.o: In function `main':
c.c:(.text+0x1a8): undefined reference to`arb_const_pi'
c.c:(.text+0x1cd): undefined reference to `flint_printf'
c.c:(.text+0x1d4): undefined reference to`arb_version'
c.c:(.text+0x1e6): undefined reference to `flint_printf'
collect2: error: ld returned 1 exit status
a@zalman:~/c/varia/arb/1$ gcc -lflint -lgmp -lmpfr -larb -I/usr/local/include -I/usr/local/include/flint/ -L/usr/local/lib  c.c
/tmp/ccdsyzvn.o: In function`_fmpz_demote':
c.c:(.text+0x28): undefined reference to `_fmpz_clear_mpz'
/tmp/ccdsyzvn.o: In function`arf_clear':
c.c:(.text+0xfc): undefined reference to `_arf_demote'
/tmp/ccdsyzvn.o: In function`arb_printn':
c.c:(.text+0x181): undefined reference to `arb_fprintn'
/tmp/ccdsyzvn.o: In function`main':
c.c:(.text+0x1a8): undefined reference to `arb_const_pi'
c.c:(.text+0x1cd): undefined reference to`flint_printf'
c.c:(.text+0x1d4): undefined reference to `arb_version'
c.c:(.text+0x1e6): undefined reference to`flint_printf'
collect2: error: ld returned 1 exit status

But I can compile arb program : 

 cd arb
a@zalman:~/arb$ build/examples/keiper_li 100
zeta: cpu/wall(s): 0.002 0.002
virt/peak/res/peak(MB): 25.09 25.09 5.61 5.61
log: cpu/wall(s): 0 0.001
gamma: cpu/wall(s): 0 0
binomial transform: cpu/wall(s): 0.001 0
0: -0.69314718055994530941723212145817656807550013436029 +/- 6.8425e-49
1: 0.023095708966121033814310247906495291621932127152268 +/- 3.9868e-48
2: 0.046172867614023335192864243096033943387066108314182 +/- 1.2738e-47
3: 0.069212973518108267930497348872601068994212026394777 +/- 4.371e-47
4: 0.092197619873060409647627872409439018065541673496812 +/- 1.4868e-46
5: 0.11510854289223549048622128109857276671349132305427 +/- 5.0294e-46
6: 0.13792766871372988290416713700341666356138966082885 +/- 1.7102e-45
7: 0.16063715965299421294040287257385366292282442055073 +/- 5.7197e-45
8: 0.1832194596433825790819393177472185984899809829119 +/- 1.8768e-44
9: 0.20565733870917046170289387421343304741236553444664 +/- 6.1276e-44
10: 0.22793393631931577436930340573684453380748386010511 +/- 2.0045e-43
91: 1.1359793878546436002006561104313275551533628689671 +/- 1.4607e-12
92: 1.1415669830327489959098935595739035602228202255345 +/- 3.3161e-12
93: 1.1471530138314698130651717448646005362180579682481 +/- 7.578e-12
94: 1.1527358323988920619177722932285812811855471805232 +/- 1.7414e-11
95: 1.1583134879564705721273560069201683049927946600968 +/- 4.019e-11
96: 1.1638837494169548403983835123477214984893522087425 +/- 9.3048e-11
97: 1.1694441288315003718368092993985140290769315690077 +/- 2.1584e-10
98: 1.1749919055490018710276285598764024158910189825872 +/- 5.0109e-10
99: 1.1805241509689506316631106075371800417317838090829 +/- 1.1631e-09
100: 1.1860377537679132994976271782020433469152756094002 +/- 2.6968e-09
virt/peak/res/peak(MB): 25.09 25.09 6.03 6.03
a@zalman:~/arb$ 

Any tips ? 
TIA

Adam

**Comment by fredrik-johansson** [comment]
Are the flint header files perhaps in some location other than /usr/local/include/flint?

Since make examples works, you can look at arb/Makefile to see what paths are set there.

**Comment by adammaj1** [comment]
I have not changed arb/Makefile  Search : locate libarb.so  /home/a/arb/libarb.so /home/a/arb/libarb.so.1 /home/a/arb/libarb.so.1.1.0 /home/a/flint2/arb/libarb.so /home/a/flint2/arb/libarb.so.1 /home/a/flint2/arb/libarb.so.1.1.0 /usr/local/lib/libarb.so /usr/local/lib/libarb.so.1 /usr/local/lib/libarb.so.1.1.0  another  search: locate ulong_extras.h  /home/a/flint2/ulong_extras.h /usr/local/include/flint/ulong_extras.h 
 

  
    Dnia 3 stycznia 2016 00:55 Fredrik Johansson &amp;lt;notifications@github.com&amp;gt; napisał(a):
  
  
    Are the flint header files perhaps in some location other than /usr/local/include/flint?

Since make examples works, you can look at arb/Makefile to see what paths are set there.

**Comment by adammaj1** [comment]
I have manually copied arb directory from home to 
/usr/local/included

Now : 
gcc  -I/usr/local/include/flint -I/usr/local/include/arb  c.c  -lgmp -lmpfr   -larb -lflint


/usr/bin/ld: /tmp/ccMryWjC.o: undefined reference to symbol '_fmpz_clear_mpz'
//usr/local/lib/libflint.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

You should mention the library on the command line after the object files being compiled:
 your simply missing a library in your make steps.
 DSO (Dynamic Shared Object)

**Comment by adammaj1** [comment]
locate libmpfr
/usr/lib/x86_64-linux-gnu/libmpfr.a
/usr/lib/x86_64-linux-gnu/libmpfr.so
/usr/lib/x86_64-linux-gnu/libmpfr.so.4
/usr/lib/x86_64-linux-gnu/libmpfr.so.4.1.2

**Comment by fredrik-johansson** [comment]
_fmpz_clear_mpz is a flint function. Somehow your libflint was not compiled correctly, installed correctly, or is not being linked correctly.

Have you tried changing the link order to -larb -lflint -lmpfr -lgmp?

**Comment by adammaj1** [comment]
gcc  -I/usr/local/include/flint -I/usr/local/include/arb  c.c -larb -lflint -lmpfr -lgmp
/usr/bin/ld: /tmp/ccXolTLx.o: undefined reference to symbol '_fmpz_clear_mpz'
//usr/local/lib/libflint.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

**Comment by argriffing** [comment]
I'm guessing it is not a coincidence that the undefined reference `_fmpz_clear_mpz` is related to threading, controlled using #ifdefs or config options like FLINT_REENTRANT, HAVE_TLS, etc. Maybe your left hand thinks that your FLINT supports multi-threading but your right hand thinks it doesn't.

**Comment by fredrik-johansson** [comment]
I think flint was not installed correctly. It's suspect that you have an /usr/local/include/nmod_vec.h; it should be /usr/local/include/flint/nmod_vec.h. Try deleting all flint header files from local/include and maybe reinstalling flint.

**Comment by adammaj1** [comment]
I have reinstalled, but still have a problems so : 
gcc -I/usr/local/include -I/usr/local/include -I/usr/local/include/flint a.c -L/usr/local/lib -L/usr/local/lib -L/usr/local/lib -larb -lflint -lmpfr -lgmp -lm -lpthread

now it works !!!
 
https://pl.wikibooks.org/wiki/Programowanie_w_systemie_UNIX/ARB

see also small change ( info about mpfr and gmp ) : 

printf("Computed with:\n arb-%s\n", arb_version);
    mpfr_printf(" MPFR-%s \n GMP-%s \n", mpfr_version, gmp_version );

**Comment by adammaj1** [comment]
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
 gcc a.c -larb -lflint -lgmp -lmpfr  -lpthread -Wall
now it works 
See also : 
https://pl.wikibooks.org/wiki/Programowanie_w_systemie_UNIX/ARB
